print("Features of python:")
print("1.Simple to learn")
print("2.Interpreted language")
print("3.Dynamically typed")
print("4.Object oriented")
print("Easy to learn")
print("Large community support")
print("Extensive library")
print("Open source and free")